language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq irssi libperl-prereqscanner-perl libperl-critic-perl
  - sudo apt-get install -qq lynx cpanminus zsh libyaml-tiny-perl libgetopt-long-descriptive-perl libwww-perl liblog-log4perl-perl libdatetime-perl libmodule-runtime-perl libparams-classify-perl libtime-duration-parse-perl
  - perl -V
  - sudo cpanm -q --skip-satisfied Perl::Critic Perl::PrereqScanner
  - git clone -q git://github.com/irssi/irssi irssi-head
  - pushd irssi-head
  - ./autogen.sh --with-perl=module 2>/dev/null | tail -17
  - make >/dev/null 2>/dev/null
  - sudo make install >/dev/null
  - popd
  - |
    if [ -f ./_testing/additional-system-deps ]; then
        sudo apt-get install -qq `cat ./_testing/additional-system-deps`
    fi
  - ./_testing/autoinstall-perl-prereqs.zsh

install:
  - true

before_script:
  - ./_testing/run-test.zsh
  - git branch -a
  - |
    if [ $TRAVIS_PULL_REQUEST != false ]; then
      git diff --stat $TRAVIS_BRANCH
    fi

script:
  - ./_testing/report-test.zsh

after_script:
  - ./_testing/show-failures.zsh

branches:
  only:
    - gh-pages
